version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      SKILLS_DB: "skills_db"
      PROJECTS_DB: "projects_db"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
